from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
# The following component tag is needed since FillProperties node is not part of the default Immersive profile 
    .addComponent(component() \
     .setLevel(3) \
     .setName("Shape") \
    ) \
    .addMeta(meta() \
     .setContent("FillProperties.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Demonstrate various FillProperties values.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("20 August 2008") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("FillPropertiesHatchStyle.png") \
     .setName("Image") \
    ) \
    .addMeta(meta() \
     .setContent("FillPropertiesHatchStyleOctaga.png") \
     .setName("Image") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://www.web3d.org/x3d/content/examples/X3dResources.html") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com") \
     .setName("subject") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/FillProperties.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Viewpoint() \
     .setDescription("FillProperties hatchStyle examples") \
     .setPosition([0,0,24]) \
    ) \
    .addChild(Transform() \
     .setDEF("OverallAdjustment") \
     .addChild(Transform() \
      .setDEF("FirstRowBoxes") \
      .setTranslation([0,7,0]) \
      .addChild(Transform() \
       .setTranslation([-9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance1") \
         .setMaterial(Material() \
          .setDiffuseColor([1,0,0]) \
         ) \
         .setFillProperties(FillProperties() \
# hatchStyle='1' horizontal equally-spaced parallel lines 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance2") \
         .setMaterial(Material() \
          .setDiffuseColor([1,0.5,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(2) \
# hatchStyle='2' vertical equally-spaced parallel lines 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance3") \
         .setMaterial(Material() \
          .setDiffuseColor([1,1,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(3) \
# hatchStyle='3' positive slope equally-spaced parallel lines 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance4") \
         .setMaterial(Material() \
          .setDiffuseColor([0,1,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(4) \
# hatchStyle='4' negative slope equally-spaced parallel lines 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance5") \
         .setMaterial(Material() \
          .setDiffuseColor([0,0,1]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(5) \
# hatchStyle='5' horizontal/vertical crosshatch 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance6") \
         .setMaterial(Material() \
          .setDiffuseColor([0,1,1]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(6) \
# hatchStyle='6' positive slope / negative slope crosshatch 
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("SecondRowText") \
      .setTranslation([0,5,0]) \
      .addChild(Transform() \
       .setTranslation([-9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["1"]) \
         .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"], size = 2, style = "BOLD") \
          .setDEF("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance1") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["2"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance2") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["3"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance3") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["4"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance4") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["5"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance5") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["6"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance6") \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("ThirdRowBoxes") \
      .setTranslation([0,2,0]) \
      .addChild(Transform() \
       .setTranslation([-9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance7") \
         .setMaterial(Material() \
          .setDiffuseColor([1,0,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(7) \
# hatchStyle='7' (optional support) cast iron or malleable iron and general use for all materials 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance8") \
         .setMaterial(Material() \
          .setDiffuseColor([1,0.5,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(8) \
# hatchStyle='8' (optional support) steel 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance9") \
         .setMaterial(Material() \
          .setDiffuseColor([1,1,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(9) \
# hatchStyle='9' (optional support) bronze, brass, copper, and compositions 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance10") \
         .setMaterial(Material() \
          .setDiffuseColor([0,1,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(10) \
# hatchStyle='10' (optional support) white metal, zinc, lead, babbit, and alloys 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance11") \
         .setMaterial(Material() \
          .setDiffuseColor([0,0,1]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(11) \
# hatchStyle='11' (optional support) magnesium, aluminum, and aluminum alloys 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance12") \
         .setMaterial(Material() \
          .setDiffuseColor([0,1,1]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(12) \
# hatchStyle='12' (optional support) rubber, plastic, and electrical insulation 
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("FourthRowText") \
      .addChild(Transform() \
       .setTranslation([-9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["7"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance7") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["8"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance8") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["9"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance9") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["10"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance10") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["11"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance11") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["12"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance12") \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("FifthRowBoxes") \
      .setTranslation([0,-3,0]) \
      .addChild(Transform() \
       .setTranslation([-9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance13") \
         .setMaterial(Material() \
          .setDiffuseColor([1,0,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(13) \
# hatchStyle='13' (optional support) cork, felt, fabric, leather, and fibre 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance14") \
         .setMaterial(Material() \
          .setDiffuseColor([1,0.5,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(14) \
# hatchStyle='14' (optional support) thermal insulation 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance15") \
         .setMaterial(Material() \
          .setDiffuseColor([1,1,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(15) \
# hatchStyle='15' (optional support) titanium and refractory material 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance16") \
         .setMaterial(Material() \
          .setDiffuseColor([0,1,0]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(16) \
# hatchStyle='16' (optional support) marble, slate, porcelain, glass, etc. 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance17") \
         .setMaterial(Material() \
          .setDiffuseColor([0,0,1]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(17) \
# hatchStyle='17' (optional support) earth 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance18") \
         .setMaterial(Material() \
          .setDiffuseColor([0,1,1]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(18) \
# hatchStyle='18' (optional support) sand 
         ) \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Box() \
        ) \
        .setAppearance(Appearance() \
         .setDEF("FillAppearance19") \
         .setMaterial(Material() \
          .setDiffuseColor([0.3,0.3,0.3]) \
         ) \
         .setFillProperties(FillProperties() \
          .setHatchStyle(19) \
# hatchStyle='19' (optional support) repeating dot 
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("SixthRowText") \
      .setTranslation([0,-5,0]) \
      .addChild(Transform() \
       .setTranslation([-9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["13"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance13") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["14"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance14") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([-3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["15"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance15") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["16"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance16") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([3,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["17"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance17") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([6,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["18"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance18") \
        ) \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([9,0,0]) \
       .addChild(Shape() \
        .setGeometry(Text() \
         .setString(["19"]) \
         .setFontStyle(FontStyle() \
          .setUSE("Middle") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("FillAppearance19") \
        ) \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures//FillProperties_RoundTrip.x3d")
