from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("PixelTextureComponentExamples.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("This example shows the five PixelTexture components, with 0 to 4 components each, shown in Table 5-18.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Leonard Daly and Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("25 August 2008") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("7 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("X3D for Web Authors, Table 5.18") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://www.web3d.org/x3d/content/examples/X3dResources.html") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("Copyright (c) 2006, Daly Realism and Don Brutzman") \
     .setName("rights") \
    ) \
    .addMeta(meta() \
     .setContent("X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com") \
     .setName("subject") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/PixelTextureComponentExamples.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Background() \
     .setSkyColor([0.1,0.1,0.4]) \
    ) \
    .addChild(Viewpoint() \
     .setDescription("Table 5.18 SFImage component examples") \
     .setPosition([0,0,14]) \
    ) \
    .addChild(Transform() \
     .setTranslation([-6,0,0]) \
     .addChild(Shape() \
      .setAppearance(Appearance() \
       .setTexture(PixelTexture() \
        .setDEF("ZeroComponents") \
       ) \
      ) \
      .setGeometry(Box() \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,-2,0]) \
      .addChild(Shape() \
       .setGeometry(Text() \
        .setString(["0"]) \
        .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"]) \
         .setDEF("CenterJustify") \
        ) \
       ) \
       .setAppearance(Appearance() \
        .setDEF("TextMaterial") \
        .setMaterial(Material() \
         .setDiffuseColor([1,1,1]) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([-3,0,0]) \
     .addChild(Shape() \
      .setAppearance(Appearance() \
       .setTexture(PixelTexture() \
        .setDEF("OneComponent") \
        .setImage([1,2,1,0xFF,0x00]) \
       ) \
      ) \
      .setGeometry(Box() \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,-2,0]) \
      .addChild(Shape() \
       .setGeometry(Text() \
        .setString(["1"]) \
        .setFontStyle(FontStyle() \
         .setUSE("CenterJustify") \
        ) \
       ) \
       .setAppearance(Appearance() \
        .setUSE("TextMaterial") \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .addChild(Shape() \
      .setAppearance(Appearance() \
       .setTexture(PixelTexture() \
        .setDEF("TwoComponents") \
        .setImage([2,1,2,0xCCFF,0x2277]) \
       ) \
      ) \
      .setGeometry(Box() \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,-2,0]) \
      .addChild(Shape() \
       .setGeometry(Text() \
        .setString(["2"]) \
        .setFontStyle(FontStyle() \
         .setUSE("CenterJustify") \
        ) \
       ) \
       .setAppearance(Appearance() \
        .setUSE("TextMaterial") \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([3,0,0]) \
     .addChild(Shape() \
      .setAppearance(Appearance() \
# note 0x000000 = 0 
       .setTexture(PixelTexture() \
        .setDEF("ThreeComponents") \
        .setImage([2,4,3,0xFF0000,0xFF00,0x000000,0,0,0,0xFFFFFF,0xFFFF00]) \
       ) \
      ) \
      .setGeometry(Box() \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,-2,0]) \
      .addChild(Shape() \
       .setGeometry(Text() \
        .setString(["3"]) \
        .setFontStyle(FontStyle() \
         .setUSE("CenterJustify") \
        ) \
       ) \
       .setAppearance(Appearance() \
        .setUSE("TextMaterial") \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([6,0,0]) \
     .addChild(Shape() \
      .setAppearance(Appearance() \
# Erroneous value in book: 1 0 0 255, 0 1 0 255, 0 0 1 255, 1 0 0 127, 0 1 0 127, 0 0 1 127 
       .setTexture(PixelTexture() \
        .setDEF("FourComponents") \
        .setImage([3,2,4,-16776961,0x00FF00FF,0x0000FFFF,-16777089,0x00FF007F,0x0000FF7F]) \
       ) \
      ) \
      .setGeometry(Box() \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,-2,0]) \
      .addChild(Shape() \
       .setGeometry(Text() \
        .setString(["4"]) \
        .setFontStyle(FontStyle() \
         .setUSE("CenterJustify") \
        ) \
       ) \
       .setAppearance(Appearance() \
        .setUSE("TextMaterial") \
       ) \
      ) \
     ) \
    ) \
# Background from PixelTextureBW.x3d 
    .addChild(Transform() \
     .setTranslation([0,6,-2]) \
     .addChild(Shape() \
      .setAppearance(Appearance() \
       .setTexture(PixelTexture() \
        .setImage([8,8,1,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0x00,0xcc,0x00,0xcc,0x00,0xcc,0x00,0xcc]) \
       ) \
      ) \
      .setGeometry(Box(size = [16,16,.1]) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures//PixelTextureComponentExamples_RoundTrip.x3d")
