from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("ElevationGridNonPlanarQuadrilaterals.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Show how a single nonplanar quadrilateral can be tesselated in 2 different ways.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("U.S. Naval Postgraduate School (NPS)") \
     .setName("organization") \
    ) \
    .addMeta(meta() \
     .setContent("28 August 2005") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("16 November 2017") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter06GeometryPointsLinesPolygons/ElevationGridNonPlanarQuadrilaterals.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(NavigationInfo() \
     .setDEF("ExamineMode") \
    ) \
    .addChild(NavigationInfo() \
     .setDEF("FlyPanNavigation") \
     .setType(["FLY","ANY"]) \
    ) \
    .addChild(Background() \
     .setSkyColor([1,1,1]) \
    ) \
    .addChild(Viewpoint() \
     .setDescription("Book View") \
     .setOrientation([0,1,0,0.01]) \
     .setPosition([0.13,0.2,7.71]) \
    ) \
    .addChild(Viewpoint() \
     .setDEF("DefaultView") \
     .setDescription("ElevationGrid tessellation examples") \
     .setPosition([0,0.2,10]) \
    ) \
    .addChild(ROUTE() \
     .setFromField("isBound") \
     .setFromNode("DefaultView") \
     .setToField("set_bind") \
     .setToNode("FlyPanNavigation") \
    ) \
    .addChild(Transform() \
     .setTranslation([0,-0.75,0]) \
     .addChild(Transform() \
      .setDEF("FigureElevationGridBack") \
      .setTranslation([-4,0,0]) \
# Note that the base of each piece of polygonal geometry is based at (1 0 1) 
      .addChild(Viewpoint() \
       .setDescription("Default brower ElevationGrid tessellation, front view") \
       .setPosition([1.5,0.4,4]) \
      ) \
      .addChild(Transform() \
       .setCenter([1,0,1]) \
       .setRotation([0,1,0,3.2]) \
       .addChild(Group() \
        .setDEF("DefaultElevationGrid") \
        .addChild(Shape() \
         .setDEF("ExampleElevationGridShape") \
         .setGeometry(ElevationGrid(height = [0,0.5,0,0], solid = False) \
          .setXDimension(2) \
          .setZDimension(2) \
         ) \
         .setAppearance(Appearance() \
          .setDEF("DiffuseRedAppearance") \
          .setMaterial(Material() \
           .setDiffuseColor([0.9,0.1,0.1]) \
           .setTransparency(0.1) \
          ) \
         ) \
        ) \
        .addChild(Transform() \
         .setDEF("FigureLabelBrowserElevationGrid") \
         .setTranslation([0.5,1,0.5]) \
         .addChild(Billboard() \
          .addChild(Shape() \
           .setGeometry(Text() \
            .setString(["Browser","ElevationGrid"]) \
            .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"], size = 0.25) \
             .setDEF("CenterFS") \
            ) \
           ) \
           .setAppearance(Appearance() \
            .setDEF("LabelAppearance") \
            .setMaterial(Material() \
             .setDiffuseColor([0.2,0.1,0.8]) \
            ) \
           ) \
          ) \
         ) \
        ) \
        .addChild(Group() \
         .setDEF("CommonFigureElements") \
         .addChild(Shape() \
          .setDEF("QuadOutlineShape") \
          .setGeometry(IndexedLineSet(colorPerVertex = False, coordIndex = [0,1,3,2,0,-1]) \
           .setColorIndex([0,0,0,0]) \
# first iterate on x-axis, then z-xis 
           .setCoord(Coordinate() \
            .setDEF("QuadrilateralPoints") \
            .setPoint([0,0,0,1,0.5,0,0,0,1,1,0,1,1,0,0]) \
           ) \
           .setColor(Color() \
            .setDEF("White") \
            .setColor([1,1,1]) \
           ) \
          ) \
         ) \
         .addChild(Shape() \
          .setDEF("FloorShape") \
# setting all height values to zero is a simple way to get a square outline. A more efficient way is to use an IndexedFaceSet. 
          .setGeometry(ElevationGrid(height = [0,0,0,0], solid = False) \
           .setXDimension(2) \
           .setZDimension(2) \
          ) \
          .setAppearance(Appearance() \
           .setDEF("TransparentGreyAppearance") \
           .setMaterial(Material() \
            .setDiffuseColor([0,0,0]) \
            .setEmissiveColor([1,1,1]) \
            .setTransparency(0.8) \
           ) \
          ) \
         ) \
         .addChild(Transform() \
          .setDEF("PointLabels") \
          .setTranslation([0,-0.2,0]) \
          .addChild(Billboard() \
           .addChild(Shape() \
            .setGeometry(Text() \
             .setString(["h0"]) \
             .setFontStyle(FontStyle() \
              .setUSE("CenterFS") \
             ) \
            ) \
            .setAppearance(Appearance() \
             .setUSE("LabelAppearance") \
            ) \
           ) \
          ) \
          .addChild(Transform() \
           .setTranslation([1,0,0]) \
           .addChild(Billboard() \
            .addChild(Shape() \
             .setGeometry(Text() \
              .setString(["h1"]) \
              .setFontStyle(FontStyle() \
               .setUSE("CenterFS") \
              ) \
             ) \
             .setAppearance(Appearance() \
              .setUSE("LabelAppearance") \
             ) \
            ) \
           ) \
          ) \
          .addChild(Transform() \
           .setTranslation([0,0,1]) \
           .addChild(Billboard() \
            .addChild(Shape() \
             .setGeometry(Text() \
              .setString(["h2"]) \
              .setFontStyle(FontStyle() \
               .setUSE("CenterFS") \
              ) \
             ) \
             .setAppearance(Appearance() \
              .setUSE("LabelAppearance") \
             ) \
            ) \
           ) \
          ) \
          .addChild(Transform() \
           .setTranslation([1,0,1]) \
           .addChild(Billboard() \
            .addChild(Shape() \
             .setGeometry(Text() \
              .setString(["h3"]) \
              .setFontStyle(FontStyle() \
               .setUSE("CenterFS") \
              ) \
             ) \
             .setAppearance(Appearance() \
              .setUSE("LabelAppearance") \
             ) \
            ) \
           ) \
          ) \
         ) \
         .addChild(Shape() \
          .setDEF("QuadVerticalLineShape") \
          .setGeometry(IndexedLineSet(colorPerVertex = False, coordIndex = [1,4,-1]) \
           .setColorIndex([0,0,0,0]) \
           .setCoord(Coordinate() \
            .setUSE("QuadrilateralPoints") \
           ) \
           .setColor(Color() \
            .setUSE("White") \
           ) \
          ) \
         ) \
        ) \
        .addChild(Shape() \
         .setDEF("QuadCrossDiagonalLineShape") \
         .setGeometry(IndexedLineSet(colorPerVertex = False, coordIndex = [2,1,-1]) \
          .setColorIndex([0,0,0,0]) \
          .setCoord(Coordinate() \
           .setUSE("QuadrilateralPoints") \
          ) \
          .setColor(Color() \
           .setUSE("White") \
          ) \
         ) \
        ) \
        .addChild(Shape() \
         .setDEF("QuadCenterDiagonalLineShape") \
         .setGeometry(IndexedLineSet(colorPerVertex = False, coordIndex = [0,3,-1]) \
          .setColorIndex([0,0,0,0]) \
          .setCoord(Coordinate() \
           .setUSE("QuadrilateralPoints") \
          ) \
          .setColor(Color() \
           .setUSE("White") \
          ) \
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("FigureElevationGridFront") \
      .setTranslation([-1,0,0]) \
      .addChild(Viewpoint() \
       .setDescription("Default brower ElevationGrid tessellation, back view") \
       .setPosition([0.5,0.4,4]) \
      ) \
      .addChild(Transform() \
       .setCenter([1,0,1]) \
       .setRotation([0,1,0,0.8]) \
       .addChild(Group() \
        .setUSE("DefaultElevationGrid") \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("FigureIfsCenterDiagonal") \
      .setTranslation([1,0,0]) \
      .addChild(Viewpoint() \
       .setDescription("Center-diagonal tessellation") \
       .setPosition([0.5,0.4,4]) \
      ) \
      .addChild(Transform() \
       .setCenter([1,0,1]) \
       .setRotation([0,1,0,0.4]) \
       .addChild(Shape() \
        .setGeometry(IndexedFaceSet(coordIndex = [0,3,1,-1,0,2,3,-1]) \
         .setCoord(Coordinate() \
          .setUSE("QuadrilateralPoints") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("DiffuseRedAppearance") \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("FigureLabelCenterDiagonalTessellation") \
        .setTranslation([0.5,1,0.5]) \
        .addChild(Billboard() \
         .addChild(Shape() \
          .setGeometry(Text() \
           .setString(["Center Diagonal","Tessellation"]) \
           .setFontStyle(FontStyle() \
            .setUSE("CenterFS") \
           ) \
          ) \
          .setAppearance(Appearance() \
           .setUSE("LabelAppearance") \
          ) \
         ) \
        ) \
       ) \
       .addChild(Group() \
        .setUSE("CommonFigureElements") \
       ) \
       .addChild(Shape() \
        .setUSE("QuadCenterDiagonalLineShape") \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("FigureIfsCrossDiagonal") \
      .setTranslation([3,0,0]) \
      .addChild(Viewpoint() \
       .setDescription("Cross-diagonal tessellation") \
       .setPosition([0.5,0.4,4]) \
      ) \
      .addChild(Transform() \
       .setCenter([1,0,1]) \
       .addChild(Shape() \
        .setGeometry(IndexedFaceSet(coordIndex = [0,2,1,-1,2,3,1,-1]) \
         .setCoord(Coordinate() \
          .setUSE("QuadrilateralPoints") \
         ) \
        ) \
        .setAppearance(Appearance() \
         .setUSE("DiffuseRedAppearance") \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("FigureLabelCrossDiagonalTessellation") \
        .setTranslation([0.5,1,0.5]) \
        .addChild(Billboard() \
         .addChild(Shape() \
          .setGeometry(Text() \
           .setString(["Cross Diagonal","Tessellation"]) \
           .setFontStyle(FontStyle() \
            .setUSE("CenterFS") \
           ) \
          ) \
          .setAppearance(Appearance() \
           .setUSE("LabelAppearance") \
          ) \
         ) \
        ) \
       ) \
       .addChild(Group() \
        .setUSE("CommonFigureElements") \
       ) \
       .addChild(Shape() \
        .setUSE("QuadCrossDiagonalLineShape") \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter06GeometryPointsLinesPolygons//ElevationGridNonPlanarQuadrilaterals_RoundTrip.x3d")
