from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("HudKelpForest.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Demonstrates use of a ProximitySensor in building a HUD, with display values showing current view location.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Leonard Daly and Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("15 July 2006") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("24 October 2016") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("HudKelpForestScreenshot.png") \
     .setName("Image") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://www.web3d.org/x3d/content/examples/X3dResources.html") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("Copyright 2006, Daly Realism and Don Brutzman") \
     .setName("rights") \
    ) \
    .addMeta(meta() \
     .setContent("X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com") \
     .setName("subject") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/HudKelpForest.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(ExternProtoDeclare() \
     .setAppinfo("Heads-up display (HUD) keeps child geometry aligned on screen in a consistent location") \
     .setName("HeadsUpDisplay") \
     .setUrl(["HeadsUpDisplayPrototype.x3d#HeadsUpDisplay","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/HeadsUpDisplayPrototype.x3d#HeadsUpDisplay","HeadsUpDisplayPrototype.wrl#HeadsUpDisplay","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/HeadsUpDisplayPrototype.wrl#HeadsUpDisplay"]) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setAppinfo("offset position for HUD relative to current view location, default 0 0 -5") \
      .setName("screenOffset") \
      .setType("SFVec3f") \
     ) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setAppinfo("X3D content positioned at HUD offset") \
      .setName("children") \
      .setType("MFNode") \
     ) \
     .addField(field() \
      .setAccessType("outputOnly") \
      .setAppinfo("HUD position update (in world coordinates) relative to original location") \
      .setName("position_changed") \
      .setType("SFVec3f") \
     ) \
     .addField(field() \
      .setAccessType("outputOnly") \
      .setAppinfo("HUD orientation update relative to original location") \
      .setName("orientation_changed") \
      .setType("SFRotation") \
     ) \
    ) \
    .addChild(ExternProtoDeclare() \
     .setName("TextString") \
     .setUrl(["TextStringPrototype.x3d#TextString","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/TextStringPrototype.x3d#TextString","TextStringPrototype.wrl#TextString","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/TextStringPrototype.wrl#TextString"]) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("offset") \
      .setType("SFVec3f") \
     ) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("string") \
      .setType("MFString") \
     ) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("color") \
      .setType("SFColor") \
     ) \
     .addField(field() \
      .setAccessType("initializeOnly") \
      .setName("size") \
      .setType("SFFloat") \
     ) \
     .addField(field() \
      .setAccessType("initializeOnly") \
      .setName("justify") \
      .setType("MFString") \
     ) \
     .addField(field() \
      .setAccessType("initializeOnly") \
      .setName("style") \
      .setType("SFString") \
     ) \
     .addField(field() \
      .setAccessType("initializeOnly") \
      .setName("family") \
      .setType("MFString") \
     ) \
    ) \
    .addChild(Background() \
     .setBackUrl(["urn:web3d:media:textures/panoramas/horizon_3_back.jpg","horizon_3_back.jpg","../../Basic/UniversalMediaPanoramas/horizon_3_back.jpg","http://www.web3d.org/WorkingGroups/media/textures/panoramas/horizon_3_back.jpg","http://www.web3d.org/x3d/content/examples/UniversalMediaPanoramas/horizon_3_back.jpg","http://www.web3dmedia.com/UniversalMedia/textures/panoramas/horizon_3_back.jpg","http://www.officetowers.com/UniversalMedia/textures/panoramas/horizon_3_back.jpg","http://geometrek.com/UniversalMedia/textures/panoramas/horizon_3_back.jpg","http://www.sc.ehu.es/ccwgamoa/UniversalMedia/textures/panoramas/horizon_3_back.jpg"]) \
     .setBottomUrl(["urn:web3d:media:textures/panoramas/horizon_3_bottom.jpg","horizon_3_bottom.jpg","../../Basic/UniversalMediaPanoramas/horizon_3_bottom.jpg","http://www.web3d.org/WorkingGroups/media/textures/panoramas/horizon_3_bottom.jpg","http://www.web3d.org/x3d/content/examples/UniversalMediaPanoramas/horizon_3_bottom.jpg","http://www.web3dmedia.com/UniversalMedia/textures/panoramas/horizon_3_bottom.jpg","http://www.officetowers.com/UniversalMedia/textures/panoramas/horizon_3_bottom.jpg","http://geometrek.com/UniversalMedia/textures/panoramas/horizon_3_bottom.jpg","http://www.sc.ehu.es/ccwgamoa/UniversalMedia/textures/panoramas/horizon_3_bottom.jpg"]) \
     .setFrontUrl(["urn:web3d:media:textures/panoramas/horizon_3_front.jpg","horizon_3_front.jpg","../../Basic/UniversalMediaPanoramas/horizon_3_front.jpg","http://www.web3d.org/WorkingGroups/media/textures/panoramas/horizon_3_front.jpg","http://www.web3d.org/x3d/content/examples/UniversalMediaPanoramas/horizon_3_front.jpg","http://www.web3dmedia.com/UniversalMedia/textures/panoramas/horizon_3_front.jpg","http://www.officetowers.com/UniversalMedia/textures/panoramas/horizon_3_front.jpg","http://geometrek.com/UniversalMedia/textures/panoramas/horizon_3_front.jpg","http://www.sc.ehu.es/ccwgamoa/UniversalMedia/textures/panoramas/horizon_3_front.jpg"]) \
     .setGroundAngle([1.309,1.5707]) \
     .setGroundColor([0.1,0.1,0,0.4,0.25,0.2,0.6,0.6,0.6]) \
     .setLeftUrl(["urn:web3d:media:textures/panoramas/horizon_3_left.jpg","horizon_3_left.jpg","../../Basic/UniversalMediaPanoramas/horizon_3_left.jpg","http://www.web3d.org/WorkingGroups/media/textures/panoramas/horizon_3_left.jpg","http://www.web3d.org/x3d/content/examples/UniversalMediaPanoramas/horizon_3_left.jpg","http://www.web3dmedia.com/UniversalMedia/textures/panoramas/horizon_3_left.jpg","http://www.officetowers.com/UniversalMedia/textures/panoramas/horizon_3_left.jpg","http://geometrek.com/UniversalMedia/textures/panoramas/horizon_3_left.jpg","http://www.sc.ehu.es/ccwgamoa/UniversalMedia/textures/panoramas/horizon_3_left.jpg"]) \
     .setRightUrl(["urn:web3d:media:textures/panoramas/horizon_3_right.jpg","horizon_3_right.jpg","../../Basic/UniversalMediaPanoramas/horizon_3_right.jpg","http://www.web3d.org/WorkingGroups/media/textures/panoramas/horizon_3_right.jpg","http://www.web3d.org/x3d/content/examples/UniversalMediaPanoramas/horizon_3_right.jpg","http://www.web3dmedia.com/UniversalMedia/textures/panoramas/horizon_3_right.jpg","http://www.officetowers.com/UniversalMedia/textures/panoramas/horizon_3_right.jpg","http://geometrek.com/UniversalMedia/textures/panoramas/horizon_3_right.jpg","http://www.sc.ehu.es/ccwgamoa/UniversalMedia/textures/panoramas/horizon_3_right.jpg"]) \
     .setSkyAngle([1.309,1.5707]) \
     .setSkyColor([0,0.5,1,0,0,1,0,0,1]) \
     .setTopUrl(["urn:web3d:media:textures/panoramas/horizon_3_top.jpg","horizon_3_top.jpg","../../Basic/UniversalMediaPanoramas/horizon_3_top.jpg","http://www.web3d.org/WorkingGroups/media/textures/panoramas/horizon_3_top.jpg","http://www.web3d.org/x3d/content/examples/UniversalMediaPanoramas/horizon_3_top.jpg","http://www.web3dmedia.com/UniversalMedia/textures/panoramas/horizon_3_top.jpg","http://www.officetowers.com/UniversalMedia/textures/panoramas/horizon_3_top.jpg","http://geometrek.com/UniversalMedia/textures/panoramas/horizon_3_top.jpg","http://www.sc.ehu.es/ccwgamoa/UniversalMedia/textures/panoramas/horizon_3_top.jpg"]) \
    ) \
    .addChild(Switch() \
     .setWhichChoice(-1) \
     .addChild(Transform() \
      .setDEF("HudContent") \
      .setTranslation([-0.5,-0.5,.1]) \
      .addChild(ProtoInstance() \
       .setDEF("TopLabel") \
       .setName("TextString") \
       .addFieldValue(fieldValue() \
        .setName("offset") \
        .setValue("-0.07 -.2 0") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("string") \
        .setValue("\"Position: \"") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("color") \
        .setValue("0 0 0") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("size") \
        .setValue(".1") \
       ) \
      ) \
      .addChild(ProtoInstance() \
       .setDEF("BottomLabel") \
       .setName("TextString") \
       .addFieldValue(fieldValue() \
        .setName("offset") \
        .setValue("-0.13 -.3 0") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("string") \
        .setValue("\"Orientation: \"") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("color") \
        .setValue("0 0 0") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("size") \
        .setValue(".1") \
       ) \
      ) \
      .addChild(ProtoInstance() \
       .setDEF("TopLine") \
       .setName("TextString") \
       .addFieldValue(fieldValue() \
        .setName("offset") \
        .setValue(".5 -.2 0") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("string") \
        .setValue("\"\"") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("color") \
        .setValue("0 0 1") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("size") \
        .setValue(".1") \
       ) \
      ) \
      .addChild(ProtoInstance() \
       .setDEF("BottomLine") \
       .setName("TextString") \
       .addFieldValue(fieldValue() \
        .setName("offset") \
        .setValue(".5 -.3 0") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("string") \
        .setValue("\"0 1 0 0\"") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("color") \
        .setValue("0.1 .7 0.1") \
       ) \
       .addFieldValue(fieldValue() \
        .setName("size") \
        .setValue(".1") \
       ) \
      ) \
      .addChild(Transform() \
       .setTranslation([0.27,-0.25,-0.1]) \
       .addChild(Shape() \
        .setGeometry(Box(size = [1.4,0.25,0.01]) \
        ) \
        .setAppearance(Appearance() \
         .setMaterial(Material() \
          .setDiffuseColor([0.9,0.9,0.9]) \
          .setTransparency(0.5) \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoInstance() \
     .setDEF("HeadsUpDisplayInstance") \
     .setName("HeadsUpDisplay") \
     .addFieldValue(fieldValue() \
      .setName("screenOffset") \
      .setValue("0.2 0.5 -2") \
     ) \
     .addFieldValue(fieldValue() \
      .setName("children") \
      .addChild(Transform() \
       .setUSE("HudContent") \
      ) \
     ) \
    ) \
    .addChild(Script() \
     .setDEF("ConvertValueScript") \
     .setUrl(["HudKelpForestScriptConvert.js","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/HudKelpForestScriptConvert.js"]) \
     .addField(field() \
      .setAccessType("inputOnly") \
      .setName("sfVec3f") \
      .setType("SFVec3f") \
     ) \
     .addField(field() \
      .setAccessType("inputOnly") \
      .setName("sfRotation") \
      .setType("SFRotation") \
     ) \
     .addField(field() \
      .setAccessType("outputOnly") \
      .setName("sfVec3fString") \
      .setType("MFString") \
     ) \
     .addField(field() \
      .setAccessType("outputOnly") \
      .setName("sfRotationString") \
      .setType("MFString") \
     ) \
    ) \
    .addChild(ROUTE() \
     .setFromField("position_changed") \
     .setFromNode("HeadsUpDisplayInstance") \
     .setToField("sfVec3f") \
     .setToNode("ConvertValueScript") \
    ) \
    .addChild(ROUTE() \
     .setFromField("orientation_changed") \
     .setFromNode("HeadsUpDisplayInstance") \
     .setToField("sfRotation") \
     .setToNode("ConvertValueScript") \
    ) \
    .addChild(ROUTE() \
     .setFromField("sfVec3fString") \
     .setFromNode("ConvertValueScript") \
     .setToField("string") \
     .setToNode("TopLine") \
    ) \
    .addChild(ROUTE() \
     .setFromField("sfRotationString") \
     .setFromNode("ConvertValueScript") \
     .setToField("string") \
     .setToNode("BottomLine") \
    ) \
    .addChild(Inline() \
     .setUrl(["../KelpForestExhibit/KelpForestMain.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpForestMain.x3d","../KelpForestExhibit//KelpForestMain.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpForestMain.wrl"]) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter14Prototypes//HudKelpForest_RoundTrip.x3d")
