from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("TextStringPrototype.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Simple Prototype for the display of text strings, combining functionality of Text and FontStyle nodes.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Leonard Daly and Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("16 July 2006") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://www.web3d.org/x3d/content/examples/X3dResources.html") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("Copyright 2006, Daly Realism and Don Brutzman") \
     .setName("rights") \
    ) \
    .addMeta(meta() \
     .setContent("X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com") \
     .setName("subject") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter14Prototypes/TextStringPrototype.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(ProtoDeclare() \
     .setName("TextString") \
     .setProtoInterface(ProtoInterface() \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("offset") \
       .setType("SFVec3f") \
       .setValue("0 0 0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("string") \
       .setType("MFString") \
      ) \
      .addField(field() \
       .setAccessType("initializeOnly") \
       .setName("size") \
       .setType("SFFloat") \
       .setValue("1.0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("color") \
       .setType("SFColor") \
       .setValue("0.2 0.6 1") \
      ) \
      .addField(field() \
       .setAccessType("initializeOnly") \
       .setName("justify") \
       .setType("MFString") \
       .setValue("\"MIDDLE\" \"MIDDLE\"") \
      ) \
      .addField(field() \
       .setAccessType("initializeOnly") \
       .setName("style") \
       .setType("SFString") \
       .setValue("PLAIN") \
      ) \
      .addField(field() \
       .setAccessType("initializeOnly") \
       .setName("family") \
       .setType("MFString") \
       .setValue("\"SANS SERIF\"") \
      ) \
     ) \
     .setProtoBody(ProtoBody() \
      .addChild(Transform() \
       .setIS(IS() \
        .addConnect(connect() \
         .setNodeField("translation") \
         .setProtoField("offset") \
        ) \
       ) \
       .addChild(Shape() \
        .setAppearance(Appearance() \
         .setMaterial(Material() \
          .setIS(IS() \
           .addConnect(connect() \
            .setNodeField("diffuseColor") \
            .setProtoField("color") \
           ) \
          ) \
         ) \
        ) \
        .setGeometry(Text() \
         .setIS(IS() \
          .addConnect(connect() \
           .setNodeField("string") \
           .setProtoField("string") \
          ) \
         ) \
         .setFontStyle(FontStyle() \
          .setIS(IS() \
           .addConnect(connect() \
            .setNodeField("family") \
            .setProtoField("family") \
           ) \
           .addConnect(connect() \
            .setNodeField("justify") \
            .setProtoField("justify") \
           ) \
           .addConnect(connect() \
            .setNodeField("size") \
            .setProtoField("size") \
           ) \
           .addConnect(connect() \
            .setNodeField("style") \
            .setProtoField("style") \
           ) \
          ) \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ProtoInstance() \
     .setDEF("MyTextStringInstance") \
     .setName("TextString") \
     .addFieldValue(fieldValue() \
      .setName("string") \
      .setValue("\"This example TextString node\" \"creates a prototype instance\" \"that combines functionality\" \"of Text and FontStyle nodes\"") \
     ) \
     .addFieldValue(fieldValue() \
      .setName("size") \
      .setValue("0.8") \
     ) \
     .addFieldValue(fieldValue() \
      .setName("style") \
      .setValue("BOLD") \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter14Prototypes//TextStringPrototype_RoundTrip.x3d")
