from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Interchange") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("NonplanarPolygons.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Illustration of nonplanar polygons.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("22 May 2006") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("Leonard Daly and Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("NonplanarPolygons.png") \
     .setName("Image") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://www.web3d.org/x3d/content/examples/X3dResources.html") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("Copyright 2006, Daly Realism and Don Brutzman") \
     .setName("rights") \
    ) \
    .addMeta(meta() \
     .setContent("X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com") \
     .setName("subject") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter13GeometryTrianglesQuadrilaterals/NonplanarPolygons.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Viewpoint() \
     .setDescription("Initial") \
    ) \
    .addChild(Viewpoint() \
     .setDescription("Book View") \
     .setOrientation([0,-1,0,0.1]) \
     .setPosition([-0.71,-0.52,8.9]) \
    ) \
    .addChild(Background() \
     .setSkyColor([1,1,1]) \
    ) \
    .addChild(NavigationInfo() \
     .setHeadlight(False) \
    ) \
    .addChild(DirectionalLight() \
     .setDirection([0,-1,0]) \
    ) \
    .addChild(Transform() \
     .setTranslation([0,2,0]) \
     .addChild(Transform() \
      .setTranslation([-2,0,0]) \
      .addChild(Shape() \
       .setDEF("SimplePoints") \
       .setAppearance(Appearance() \
        .setDEF("Black") \
        .setMaterial(Material() \
         .setDiffuseColor([0,0,0]) \
         .setSpecularColor([1,0,0]) \
        ) \
       ) \
       .setGeometry(PointSet() \
        .setCoord(Coordinate() \
         .setDEF("Points") \
         .setPoint([-1,-1,3,1,-2,3,1,-1,1,-1,-2,1]) \
        ) \
       ) \
      ) \
      .addChild(Group() \
       .setDEF("OutlineWithExaggeratedPoints") \
       .addChild(Shape() \
        .setAppearance(Appearance() \
         .setUSE("Black") \
        ) \
        .setGeometry(IndexedLineSet(coordIndex = [0,1,2,3,0,-1]) \
         .setCoord(Coordinate() \
          .setUSE("Points") \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setTranslation([-1,-1,3]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("Black") \
         ) \
         .setGeometry(Sphere(radius = .1) \
          .setDEF("Ball") \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setTranslation([1,-2,3]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("Black") \
         ) \
         .setGeometry(Sphere() \
          .setUSE("Ball") \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setTranslation([1,-1,1]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("Black") \
         ) \
         .setGeometry(Sphere() \
          .setUSE("Ball") \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setTranslation([-1,-2,1]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("Black") \
         ) \
         .setGeometry(Sphere() \
          .setUSE("Ball") \
         ) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([2,0,0]) \
      .addChild(Group() \
       .setUSE("OutlineWithExaggeratedPoints") \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([-2,0,0]) \
     .addChild(Shape() \
      .setGeometry(IndexedFaceSet(coordIndex = [0,1,2,-1,2,3,0,-1], creaseAngle = 1.57, solid = False) \
       .setCoord(Coordinate() \
        .setUSE("Points") \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setDEF("Look") \
       .setMaterial(Material() \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([2,0,0]) \
     .addChild(Shape() \
      .setGeometry(IndexedFaceSet(coordIndex = [0,1,3,-1,1,2,3,-1], creaseAngle = 1.57, solid = False) \
       .setCoord(Coordinate() \
        .setUSE("Points") \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setUSE("Look") \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter13GeometryTrianglesQuadrilaterals//NonplanarPolygons_RoundTrip.x3d")
