from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("BooleanTogglePumpHouse.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("A BooleanToggle node controls pump house animation: select to stop, then select again to restart.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Todd Gagnon and Mark A. Boyd") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("Xeena VRML importer, X3D-Edit 3.1, http://www.web3d.org/x3d/content/README.X3D-Edit.html") \
     .setName("translator") \
    ) \
    .addMeta(meta() \
     .setContent("8 June 1998") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("20 December 2002") \
     .setName("translated") \
    ) \
    .addMeta(meta() \
     .setContent("10 October 2015") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("KelpTank.x3d") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/PumpHouse.x3d") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/BooleanTogglePumpHouse.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("Vrml97ToX3dNist, http://ovrt.nist.gov/v2_x3d.html") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Background() \
     .setSkyColor([1,1,1]) \
    ) \
    .addChild(Viewpoint() \
     .setDescription("Click pump house to toggle operation") \
     .setOrientation([-0.969,0.239,0.056,0.13]) \
     .setPosition([1.66,1.34,5.95]) \
    ) \
    .addChild(Group() \
     .addChild(Transform() \
      .setScale([0.91,0.6,0.3]) \
      .setTranslation([0.8,-0.65,0.5]) \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([0.749,0.694,0.651]) \
        ) \
       ) \
       .setGeometry(Cylinder(bottom = False) \
        .setTop(False) \
       ) \
      ) \
     ) \
     .addChild(Group() \
      .addChild(TouchSensor() \
       .setDEF("PumpTouched") \
       .setDescription("touch to activate") \
      ) \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setDEF("PumpHouseAppearance") \
        .setMaterial(Material() \
         .setDiffuseColor([0.82,0.78,0.74]) \
        ) \
       ) \
       .setGeometry(IndexedFaceSet(coordIndex = [0,1,5,4,-1,5,1,2,6,-1,6,2,3,7,-1,3,0,4,7,-1,1,12,13,2,-1,2,13,14,-1,12,15,16,13,-1,15,0,3,16,-1,16,3,17,-1,9,5,6,10,-1,8,9,10,11,-1,4,8,11,7,-1,4,5,9,8,-1,11,10,6,7,-1,3,2,14,17,-1,13,16,17,14,-1]) \
        .setCoord(Coordinate() \
         .setPoint([0.0,0.0,0.0,2.0,0.0,0.0,2.0,1.75,0.0,0.0,1.75,0.0,0.625,0.75,0.0,1.0,0.75,0.0,1.0,1.6,0.0,0.625,1.6,0.0,0.625,0.75,-0.65,1.0,0.75,-0.65,1.0,1.6,-0.65,0.625,1.6,-0.65,2.0,0.0,-2.7,2.0,1.75,-2.7,2.0,2.5,-1.0,0.0,0.0,-2.7,0.0,1.75,-2.7,0.0,2.5,-1.0]) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(Group() \
     .addChild(Transform() \
      .setScale([0.5,0.5,0.5]) \
      .setTranslation([1.0,1.1,-1.5]) \
      .addChild(Transform() \
       .setDEF("PistonTransform") \
       .addChild(Transform() \
        .setScale([1.8,1.2,0.6]) \
        .setTranslation([0.0,-0.2,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setMaterial(Material() \
           .setDiffuseColor([0.427,0.427,0.42]) \
          ) \
         ) \
         .setGeometry(Cylinder(height = 1.0, radius = 0.98) \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("CylinderRod") \
        .setRotation([0.0,0.0,-1.0,0.523599]) \
        .setTranslation([-0.25,0.75,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("PumpHouseAppearance") \
         ) \
         .setGeometry(Cylinder(height = 1.0, radius = 0.1) \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setRotation([0.0,0.0,1.0,1.047198]) \
        .setTranslation([1.0,0.6,0.0]) \
        .addChild(Transform() \
         .setUSE("CylinderRod") \
        ) \
       ) \
       .addChild(Transform() \
        .setTranslation([0.0,1.2,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("PumpHouseAppearance") \
         ) \
         .setGeometry(Sphere(radius = 0.15) \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("RockerArm1") \
        .setCenter([0.0,-0.4,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("PumpHouseAppearance") \
         ) \
         .setGeometry(Cylinder(height = 1.8, radius = 0.1) \
         ) \
        ) \
        .addChild(Transform() \
         .setTranslation([0.0,0.95,0.0]) \
         .addChild(Shape() \
          .setAppearance(Appearance() \
           .setUSE("PumpHouseAppearance") \
          ) \
          .setGeometry(Sphere(radius = 0.15) \
          ) \
         ) \
        ) \
        .addChild(PositionInterpolator() \
         .setDEF("Rocker1Path") \
         .setKey([0.0,0.3,0.32,0.5,0.75,1.0]) \
         .setKeyValue([0.0,2.0,-0.25,0.0,1.8,-0.35,0.0,1.8,-0.35,0.0,2.0,-0.25,0.0,2.0,-0.12,0.0,2.0,-0.25]) \
        ) \
        .addChild(OrientationInterpolator() \
         .setDEF("Rocker1Rotation") \
         .setKey([0.0,0.3,0.32,0.5,0.75,1.0]) \
         .setKeyValue([-1.0,0.0,0.0,0.523599,-1.0,0.0,0.0,1.0471976,-1.0,0.0,0.0,1.0471976,-1.0,0.0,0.0,0.523599,-1.0,0.0,0.0,0.2617994,-1.0,0.0,0.0,0.523599]) \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("RockerArm2") \
        .setCenter([0.0,0.7,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setUSE("PumpHouseAppearance") \
         ) \
         .setGeometry(Cylinder(height = 1.8, radius = 0.1) \
         ) \
        ) \
        .addChild(Transform() \
         .setTranslation([0.0,-0.95,0.0]) \
         .addChild(Shape() \
          .setAppearance(Appearance() \
           .setUSE("PumpHouseAppearance") \
          ) \
          .setGeometry(Sphere(radius = 0.15) \
          ) \
         ) \
        ) \
        .addChild(PositionInterpolator() \
         .setDEF("Rocker2Path") \
         .setKey([0.0,0.3,0.32,0.5,0.75,1.0]) \
         .setKeyValue([0.0,1.95,-1.0,0.0,1.2,-1.6,0.0,1.2,-1.6,0.0,1.95,-1.0,0.0,2.2,-0.65,0.0,1.95,-1.0]) \
        ) \
        .addChild(OrientationInterpolator() \
         .setDEF("Rocker2Rotation") \
         .setKey([0.0,0.3,0.32,0.5,0.75,1.0]) \
         .setKeyValue([1.0,0.0,0.0,0.523599,1.0,0.0,0.0,0.4,1.0,0.0,0.0,0.4,1.0,0.0,0.0,0.523599,1.0,0.0,0.0,1.570796,1.0,0.0,0.0,0.523599]) \
        ) \
       ) \
      ) \
      .addChild(TimeSensor() \
       .setDEF("PistonClock") \
       .setCycleInterval(5.5) \
       .setLoop(True) \
       .setStartTime(1) \
      ) \
      .addChild(PositionInterpolator() \
       .setDEF("PistonPath") \
       .setKey([0.0,0.3,0.32,0.5,0.75,1.0]) \
       .setKeyValue([-0.4,-2.3,4.0,-0.4,-1.5,4.0,-0.4,-1.5,4.0,-0.4,-2.3,4.0,-0.4,-3.3,4.0,-0.4,-2.3,4.0]) \
      ) \
      .addChild(BooleanToggle() \
       .setDEF("Toggler") \
      ) \
      .addChild(BooleanFilter() \
       .setDEF("Tee") \
      ) \
      .addChild(TimeTrigger() \
       .setDEF("PauseOn") \
      ) \
      .addChild(TimeTrigger() \
       .setDEF("PauseOff") \
      ) \
     ) \
    ) \
    .addChild(Script() \
     .setDEF("Dump") \
     .setUrl(["BooleanTogglePumpHouseScript.js","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/BooleanTogglePumpHouseScript.js"]) \
     .addField(field() \
      .setAccessType("inputOnly") \
      .setName("dumpSFBool") \
      .setType("SFBool") \
     ) \
     .addField(field() \
      .setAccessType("inputOnly") \
      .setName("dumpSFTime") \
      .setType("SFTime") \
     ) \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("PumpTouched") \
     .setToField("set_boolean") \
     .setToNode("Toggler") \
    ) \
    .addChild(ROUTE() \
     .setFromField("inputTrue") \
     .setFromNode("Tee") \
     .setToField("dumpSFBool") \
     .setToNode("Dump") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerTime") \
     .setFromNode("PauseOn") \
     .setToField("dumpSFTime") \
     .setToNode("Dump") \
    ) \
    .addChild(ROUTE() \
     .setFromField("toggle_changed") \
     .setFromNode("Toggler") \
     .setToField("set_boolean") \
     .setToNode("Tee") \
    ) \
    .addChild(ROUTE() \
     .setFromField("inputTrue") \
     .setFromNode("Tee") \
     .setToField("set_boolean") \
     .setToNode("PauseOn") \
    ) \
    .addChild(ROUTE() \
     .setFromField("inputFalse") \
     .setFromNode("Tee") \
     .setToField("set_boolean") \
     .setToNode("PauseOff") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerTime") \
     .setFromNode("PauseOn") \
     .setToField("pauseTime") \
     .setToNode("PistonClock") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerTime") \
     .setFromNode("PauseOff") \
     .setToField("resumeTime") \
     .setToNode("PistonClock") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("PistonClock") \
     .setToField("set_fraction") \
     .setToNode("PistonPath") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("PistonPath") \
     .setToField("set_translation") \
     .setToNode("PistonTransform") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("PistonClock") \
     .setToField("set_fraction") \
     .setToNode("Rocker1Path") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("Rocker1Path") \
     .setToField("set_translation") \
     .setToNode("RockerArm1") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("PistonClock") \
     .setToField("set_fraction") \
     .setToNode("Rocker1Rotation") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("Rocker1Rotation") \
     .setToField("set_rotation") \
     .setToNode("RockerArm1") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("PistonClock") \
     .setToField("set_fraction") \
     .setToNode("Rocker2Path") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("Rocker2Path") \
     .setToField("set_translation") \
     .setToNode("RockerArm2") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("PistonClock") \
     .setToField("set_fraction") \
     .setToNode("Rocker2Rotation") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("Rocker2Rotation") \
     .setToField("set_rotation") \
     .setToNode("RockerArm2") \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting//BooleanTogglePumpHouse_RoundTrip.x3d")
