from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Interchange") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("CircleLinesExample.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Example circle and cross-hairs made out of line segments, autogenerated by a simple Java program.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("14 November 2009") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("28 July 2011") \
     .setName("generated") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/CircleLinesExample.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("CircleLines.java") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/CircleLines.java") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
# CircleLines is an IndexedLineSet made out of 24 line segments 
    .addChild(Viewpoint() \
     .setDescription("CircleLines Example") \
     .setPosition([0,0,4]) \
    ) \
    .addChild(Shape() \
     .setGeometry(IndexedLineSet(coordIndex = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,-1,24,25,-1,26,27,-1]) \
      .setCoord(Coordinate() \
       .setPoint([0.000,1.000,0.0,0.259,0.966,0.0,0.500,0.866,0.0,0.707,0.707,0.0,0.866,0.500,0.0,0.966,0.259,0.0,1.000,0.000,0.0,0.966,-0.259,0.0,0.866,-0.500,0.0,0.707,-0.707,0.0,0.500,-0.866,0.0,0.259,-0.966,0.0,0.000,-1.000,0.0,-0.259,-0.966,0.0,-0.500,-0.866,0.0,-0.707,-0.707,0.0,-0.866,-0.500,0.0,-0.966,-0.259,0.0,-1.000,-0.000,0.0,-0.966,0.259,0.0,-0.866,0.500,0.0,-0.707,0.707,0.0,-0.500,0.866,0.0,-0.259,0.966,0.0,0,1,0,0,-1,0,1,0,0,-1,0,0]) \
      ) \
     ) \
     .setAppearance(Appearance() \
      .setMaterial(Material() \
       .setEmissiveColor([1,.5,.2]) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting//CircleLinesExample_RoundTrip.x3d")
