from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("MoodSelector.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Design pattern demonstrating multiple TouchSensor, IntegerTrigger, Shape and ROUTE combinations for selecting a Switch") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Jason Nelson and MV4205 class") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("6 April 2009") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("smiley images are open source") \
     .setName("license") \
    ) \
    .addMeta(meta() \
     .setContent("http://openclipart.org/media/tags/smiley") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/MoodSelector.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Viewpoint() \
     .setDescription("How do you feel today?") \
     .setPosition([0,0,15]) \
    ) \
    .addChild(Transform() \
     .setTranslation([0,3,0]) \
     .addChild(TouchSensor() \
      .setDEF("howFeelText") \
      .setDescription("Touch to select your mood face") \
     ) \
     .addChild(Shape() \
      .setGeometry(Text() \
       .setString(["How do you feel today?"]) \
       .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"]) \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([-5,0,0]) \
     .addChild(TouchSensor() \
      .setDEF("happyText") \
      .setDescription("I feel happy I feel happy...") \
     ) \
     .addChild(Shape() \
      .setGeometry(Text() \
       .setString(["Happy"]) \
       .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"]) \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
        .setDiffuseColor([0.129412,1,0.019608]) \
       ) \
      ) \
     ) \
     .addChild(Shape() \
      .setGeometry(Box(size = [2.5,1,0.1]) \
      ) \
      .setAppearance(Appearance() \
       .setDEF("TransparentAppearance") \
       .setMaterial(Material() \
        .setTransparency(1) \
       ) \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([-1.3,0,0]) \
     .addChild(TouchSensor() \
      .setDEF("notBadText") \
      .setDescription("OK mediocre just plain average no comment") \
     ) \
     .addChild(Shape() \
      .setGeometry(Text() \
       .setString(["Average"]) \
       .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"]) \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
        .setDiffuseColor([1,0.960784,0.019608]) \
       ) \
      ) \
     ) \
     .addChild(Shape() \
      .setGeometry(Box(size = [3,1,0.1]) \
      ) \
      .setAppearance(Appearance() \
       .setUSE("TransparentAppearance") \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([2.2,0,0]) \
     .addChild(TouchSensor() \
      .setDEF("sadText") \
      .setDescription("Poor poor pitiful me") \
     ) \
     .addChild(Shape() \
      .setGeometry(Text() \
       .setString(["Sad"]) \
       .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"]) \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
        .setDiffuseColor([0.180392,0.705882,1]) \
       ) \
      ) \
     ) \
     .addChild(Shape() \
      .setGeometry(Box(size = [2,1,0.1]) \
      ) \
      .setAppearance(Appearance() \
       .setUSE("TransparentAppearance") \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setTranslation([5,0,0]) \
     .addChild(TouchSensor() \
      .setDEF("badText") \
      .setDescription("Look out below!") \
     ) \
     .addChild(Shape() \
      .setGeometry(Text() \
       .setString(["Bad"]) \
       .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"]) \
       ) \
      ) \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
        .setDiffuseColor([1,0.019608,0.05098]) \
       ) \
      ) \
     ) \
     .addChild(Shape() \
      .setGeometry(Box(size = [4.5,1,0.1]) \
      ) \
      .setAppearance(Appearance() \
       .setUSE("TransparentAppearance") \
      ) \
     ) \
    ) \
    .addChild(Switch() \
     .setDEF("display") \
     .setWhichChoice(-1) \
     .addChild(Transform() \
      .setTranslation([-5,-3,0]) \
      .addChild(Shape() \
       .setDEF("happyimg") \
       .setGeometry(Box() \
       ) \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([0,0.819608,0.156863]) \
        ) \
        .setTexture(ImageTexture() \
         .setUrl(["images/nicubunu_Emoticons_Laughing_face.png","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/images/nicubunu_Emoticons_Laughing_face.png"]) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([-1.3,-3,0]) \
      .addChild(Shape() \
       .setDEF("nbimg") \
       .setGeometry(Box() \
       ) \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([0,0.066667,0.941176]) \
        ) \
        .setTexture(ImageTexture() \
         .setUrl(["images/nicubunu_Emoticons_Worried_face.png","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/images/nicubunu_Emoticons_Worried_face.png"]) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([2.2,-3,0]) \
      .addChild(Shape() \
       .setDEF("sadimg") \
       .setGeometry(Box() \
       ) \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([0.980392,0.968627,0]) \
        ) \
        .setTexture(ImageTexture() \
         .setUrl(["images/nicubunu_Emoticons_Crying_face.png","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/images/nicubunu_Emoticons_Crying_face.png"]) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([4.7,-3,0]) \
      .addChild(Shape() \
       .setDEF("bullimg") \
       .setGeometry(Box() \
       ) \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([1,0.101961,0.180392]) \
        ) \
        .setTexture(ImageTexture() \
         .setUrl(["images/nicubunu_Emoticons_Devil_face.png","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/images/nicubunu_Emoticons_Devil_face.png"]) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(IntegerTrigger() \
     .setDEF("nodisplay") \
     .setIntegerKey(-1) \
    ) \
    .addChild(IntegerTrigger() \
     .setDEF("happydisplay") \
     .setIntegerKey(0) \
    ) \
    .addChild(IntegerTrigger() \
     .setDEF("nbdisplay") \
     .setIntegerKey(1) \
    ) \
    .addChild(IntegerTrigger() \
     .setDEF("saddisplay") \
     .setIntegerKey(2) \
    ) \
    .addChild(IntegerTrigger() \
     .setDEF("bulldisplay") \
     .setIntegerKey(3) \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("howFeelText") \
     .setToField("set_boolean") \
     .setToNode("nodisplay") \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("happyText") \
     .setToField("set_boolean") \
     .setToNode("happydisplay") \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("notBadText") \
     .setToField("set_boolean") \
     .setToNode("nbdisplay") \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("sadText") \
     .setToField("set_boolean") \
     .setToNode("saddisplay") \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("badText") \
     .setToField("set_boolean") \
     .setToNode("bulldisplay") \
    ) \
# Note that Switch \"which choice\" has FAN IN 
    .addChild(ROUTE() \
     .setFromField("triggerValue") \
     .setFromNode("nodisplay") \
     .setToField("whichChoice") \
     .setToNode("display") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerValue") \
     .setFromNode("happydisplay") \
     .setToField("whichChoice") \
     .setToNode("display") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerValue") \
     .setFromNode("nbdisplay") \
     .setToField("whichChoice") \
     .setToNode("display") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerValue") \
     .setFromNode("saddisplay") \
     .setToField("whichChoice") \
     .setToNode("display") \
    ) \
    .addChild(ROUTE() \
     .setFromField("triggerValue") \
     .setFromNode("bulldisplay") \
     .setToField("whichChoice") \
     .setToNode("display") \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting//MoodSelector_RoundTrip.x3d")
