from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("ScriptSimpleStateEvents.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("A Script node drives an animated push button that turns a light on and off.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Leonard Daly and Don Brutzman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("10 June 2006") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://www.web3d.org/x3d/content/examples/X3dResources.html") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("Copyright 2006, Daly Realism and Don Brutzman") \
     .setName("rights") \
    ) \
    .addMeta(meta() \
     .setContent("X3D book, X3D graphics, X3D-Edit, http://www.x3dGraphics.com") \
     .setName("subject") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/ScriptSimpleStateEvents.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Background() \
     .setSkyColor([1,1,1]) \
    ) \
    .addChild(Viewpoint() \
     .setDescription("click switch to toggle light") \
     .setOrientation([-0.993,0.101,-0.063,1.06]) \
     .setPosition([0.06,3.63,2.29]) \
    ) \
    .addChild(Transform() \
     .setDEF("PushBox") \
     .setTranslation([-2,0,0]) \
     .addChild(Transform() \
      .setDEF("ControlBox") \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([0,.8,0]) \
        ) \
       ) \
       .setGeometry(Box(size = [1,.5,1]) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("ControlButton") \
      .setTranslation([0,.25,0]) \
      .addChild(TouchSensor() \
       .setDEF("ButtonTouch") \
       .setDescription("touch to toggle") \
      ) \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDiffuseColor([1,0,0]) \
        ) \
       ) \
       .setGeometry(Cylinder(bottom = False, height = .5, radius = .25) \
        .setDEF("Button") \
       ) \
      ) \
      .addChild(PositionInterpolator() \
       .setDEF("ButtonMover") \
       .setKey([0,1]) \
       .setKeyValue([0,.25,0,0,.05,0]) \
      ) \
      .addChild(TimeSensor() \
       .setDEF("ButtonTimer") \
      ) \
      .addChild(ROUTE() \
       .setFromField("touchTime") \
       .setFromNode("ButtonTouch") \
       .setToField("startTime") \
       .setToNode("ButtonTimer") \
      ) \
      .addChild(ROUTE() \
       .setFromField("fraction_changed") \
       .setFromNode("ButtonTimer") \
       .setToField("set_fraction") \
       .setToNode("ButtonMover") \
      ) \
      .addChild(ROUTE() \
       .setFromField("value_changed") \
       .setFromNode("ButtonMover") \
       .setToField("translation") \
       .setToNode("ControlButton") \
      ) \
     ) \
    ) \
    .addChild(Transform() \
     .setDEF("Lamp") \
     .setTranslation([1,0,0]) \
     .addChild(Transform() \
      .setDEF("Base") \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
        ) \
       ) \
       .setGeometry(Cylinder(height = .5, radius = .25) \
       ) \
      ) \
     ) \
     .addChild(Transform() \
      .setDEF("Bulb") \
      .setTranslation([0,.5,0]) \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setMaterial(Material() \
         .setDEF("LightBulbMaterial") \
         .setDiffuseColor([.4,.4,.4]) \
        ) \
       ) \
       .setGeometry(Sphere(radius = .5) \
       ) \
      ) \
     ) \
    ) \
    .addChild(Script() \
     .setDEF("ControlScript") \
     .setUrl(["ScriptSimpleStateEvents.js","http://X3dGraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/ScriptSimpleStateEvents.js"]) \
     .addField(field() \
      .setAccessType("initializeOnly") \
      .setName("buttonDown") \
      .setType("SFBool") \
      .setValue("false") \
     ) \
     .addField(field() \
      .setAccessType("inputOnly") \
      .setName("buttonTimerActive") \
      .setType("SFBool") \
     ) \
     .addField(field() \
      .setAccessType("outputOnly") \
      .setName("newButtonPath") \
      .setType("MFVec3f") \
     ) \
     .addField(field() \
      .setAccessType("outputOnly") \
      .setName("lightColor") \
      .setType("SFColor") \
     ) \
    ) \
    .addChild(ROUTE() \
     .setFromField("isActive") \
     .setFromNode("ButtonTimer") \
     .setToField("buttonTimerActive") \
     .setToNode("ControlScript") \
    ) \
    .addChild(ROUTE() \
     .setFromField("newButtonPath") \
     .setFromNode("ControlScript") \
     .setToField("keyValue") \
     .setToNode("ButtonMover") \
    ) \
    .addChild(ROUTE() \
     .setFromField("lightColor") \
     .setFromNode("ControlScript") \
     .setToField("diffuseColor") \
     .setToNode("LightBulbMaterial") \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting//ScriptSimpleStateEvents_RoundTrip.x3d")
