from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Interactive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("CopperRockfishPlacardViewer.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Viewer for tank placards - needs photo on one side, placard on other, and conversion into prototype once ready.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("1 April 2002") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("13 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("Todd Gagnon and Mark A. Boyd") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/CopperRockfishPlacardViewer.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(Viewpoint() \
     .setDEF("CopperRockfish") \
     .setDescription("Copper Rockfish") \
     .setPosition([0.0,0.0,4.0]) \
    ) \
    .addChild(Group() \
     .addChild(TouchSensor() \
      .setDEF("BlueRockfishTouchSensor") \
      .setDescription("touch to rotate") \
     ) \
     .addChild(TimeSensor() \
      .setDEF("BLUEROCKFISHCLOCK") \
      .setCycleInterval(2.0) \
     ) \
     .addChild(OrientationInterpolator() \
      .setDEF("BlueRockfishPathInterpolator") \
      .setKey([0.0,0.5,1.0]) \
      .setKeyValue([0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.57,0.0,1.0,0.0,3.14]) \
     ) \
     .addChild(Transform() \
      .setDEF("BLUEROCKFISH_TRANSFORM") \
      .addChild(Shape() \
       .setAppearance(Appearance() \
        .setTexture(ImageTexture() \
         .setDEF("CopperRockfishImage") \
         .setUrl(["CopperRockfishPlacard.jpg","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/CopperRockfishPlacard.jpg"]) \
        ) \
        .setTextureTransform(TextureTransform() \
         .setScale([1,2]) \
        ) \
       ) \
       .setGeometry(IndexedFaceSet(coordIndex = [0,1,2,3,0,-1]) \
        .setCoord(Coordinate() \
         .setPoint([-2,-1,0,2,-1,0,2,1,0,-2,1,0]) \
        ) \
       ) \
      ) \
     ) \
     .addChild(Group() \
      .addChild(Transform() \
       .setDEF("BUTTON_TRANSFORM") \
       .setTranslation([1.0,2.0,0.0]) \
       .addChild(Shape() \
        .setAppearance(Appearance() \
         .setMaterial(Material() \
          .setDiffuseColor([0.0,1.0,0.0]) \
         ) \
        ) \
        .setGeometry(Sphere(radius = 0.5) \
        ) \
       ) \
      ) \
      .addChild(TouchSensor() \
       .setDEF("FrontTouchSensor") \
       .setDescription("touch to rotate") \
      ) \
      .addChild(TimeSensor() \
       .setDEF("FRONTTOUCHSENSORCLOCK") \
       .setCycleInterval(2.0) \
      ) \
      .addChild(OrientationInterpolator() \
       .setDEF("PlaqueToPictureInterpolator") \
       .setKey([0.0,0.5,1.0]) \
       .setKeyValue([0.0,1.0,0.0,3.14,0.0,1.0,0.0,1.57,0.0,1.0,0.0,0.0]) \
      ) \
     ) \
     .addChild(Group() \
      .addChild(Transform() \
       .setDEF("BUTTON_TRANSFORM2") \
       .setTranslation([-1.0,2.0,0.0]) \
       .addChild(Shape() \
        .setAppearance(Appearance() \
         .setMaterial(Material() \
          .setDiffuseColor([1.0,0.0,0.0]) \
         ) \
        ) \
        .setGeometry(Sphere(radius = 0.5) \
        ) \
       ) \
      ) \
      .addChild(TouchSensor() \
       .setDEF("PictureTouchSensor") \
       .setDescription("touch to rotate") \
      ) \
     ) \
     .addChild(Group() \
      .addChild(Transform() \
       .setDEF("BASE_TRANSFORM") \
       .setTranslation([0.0,0.0,-0.3]) \
       .addChild(Shape() \
        .setAppearance(Appearance() \
         .setMaterial(Material() \
          .setDiffuseColor([0.3,0.3,0.6]) \
         ) \
        ) \
        .setGeometry(Box(size = [8.0,6.0,0.3]) \
        ) \
       ) \
      ) \
      .addChild(Group() \
       .addChild(Transform() \
        .setTranslation([0.0,-2.6,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setMaterial(Material() \
           .setDiffuseColor([0.8,0.8,0.2]) \
          ) \
         ) \
         .setGeometry(Box(size = [8.0,1.0,1.0]) \
         ) \
        ) \
       ) \
      ) \
      .addChild(Group() \
       .addChild(Transform() \
        .setTranslation([0.0,2.6,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setMaterial(Material() \
           .setDiffuseColor([0.8,0.8,0.2]) \
          ) \
         ) \
         .setGeometry(Box(size = [8.0,1.0,1.0]) \
         ) \
        ) \
       ) \
      ) \
      .addChild(Group() \
       .addChild(Transform() \
        .setRotation([0.0,0.0,1.0,1.58]) \
        .setTranslation([3.6,0.0,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setMaterial(Material() \
           .setDiffuseColor([0.8,0.8,0.2]) \
          ) \
         ) \
         .setGeometry(Box(size = [6.2,1.0,1.0]) \
         ) \
        ) \
       ) \
      ) \
      .addChild(Group() \
       .addChild(Transform() \
        .setRotation([0.0,0.0,1.0,1.58]) \
        .setTranslation([-3.6,0.0,0.0]) \
        .addChild(Shape() \
         .setAppearance(Appearance() \
          .setMaterial(Material() \
           .setDiffuseColor([0.8,0.8,0.2]) \
          ) \
         ) \
         .setGeometry(Box(size = [6.2,1.0,1.0]) \
         ) \
        ) \
       ) \
      ) \
     ) \
    ) \
    .addChild(ROUTE() \
     .setFromField("touchTime") \
     .setFromNode("BlueRockfishTouchSensor") \
     .setToField("set_startTime") \
     .setToNode("BLUEROCKFISHCLOCK") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("BLUEROCKFISHCLOCK") \
     .setToField("set_fraction") \
     .setToNode("BlueRockfishPathInterpolator") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("BlueRockfishPathInterpolator") \
     .setToField("set_rotation") \
     .setToNode("BLUEROCKFISH_TRANSFORM") \
    ) \
    .addChild(ROUTE() \
     .setFromField("touchTime") \
     .setFromNode("FrontTouchSensor") \
     .setToField("set_startTime") \
     .setToNode("FRONTTOUCHSENSORCLOCK") \
    ) \
    .addChild(ROUTE() \
     .setFromField("fraction_changed") \
     .setFromNode("FRONTTOUCHSENSORCLOCK") \
     .setToField("set_fraction") \
     .setToNode("PlaqueToPictureInterpolator") \
    ) \
    .addChild(ROUTE() \
     .setFromField("value_changed") \
     .setFromNode("PlaqueToPictureInterpolator") \
     .setToField("set_rotation") \
     .setToNode("BLUEROCKFISH_TRANSFORM") \
    ) \
    .addChild(ROUTE() \
     .setFromField("touchTime") \
     .setFromNode("PictureTouchSensor") \
     .setToField("set_startTime") \
     .setToNode("BLUEROCKFISHCLOCK") \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/KelpForestExhibit//CopperRockFishPlacardViewer_RoundTrip.x3d")
