from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("FishModelComparison.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("This file compares all of the fish prototypes.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Scott Tufts") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("17 December 2001") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("21 March 2009") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/FishModelComparison.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(ExternProtoDeclare() \
     .setName("SeaStar") \
     .setUrl(["SeaStarPrototype.x3d#SeaStar","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/SeaStarPrototype.x3d#SeaStar","SeaStarPrototype.wrl#SeaStar","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/SeaStarPrototype.wrl#SeaStar"]) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("skinDifColor") \
      .setType("SFColor") \
     ) \
    ) \
    .addChild(ExternProtoDeclare() \
     .setAppinfo("HalfMoon fish") \
     .setName("HalfMoon") \
     .setUrl(["HalfMoonPrototype.x3d#HalfMoon","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/HalfMoonPrototype.x3d#HalfMoon","HalfMoonPrototype.wrl#HalfMoon","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/HalfMoonPrototype.wrl#HalfMoon"]) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("skinTextureUrl") \
      .setType("MFString") \
     ) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("fishScale") \
      .setType("SFVec3f") \
     ) \
     .addField(field() \
      .setAccessType("inputOutput") \
      .setName("fishColor") \
      .setType("SFColor") \
     ) \
    ) \
    .addChild(Transform() \
     .setRotation([1,0,0,3.14]) \
     .addChild(Transform() \
      .setTranslation([2,0,0]) \
      .addChild(ProtoInstance() \
       .setName("SeaStar") \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([1,0,0]) \
      .addChild(Inline() \
       .setUrl(["BlackSurfPerch.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/BlackSurfPerch.x3d","BlackSurfPerch.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/BlackSurfPerch.wrl"]) \
      ) \
     ) \
     .addChild(Transform() \
      .addChild(ProtoInstance() \
       .setName("HalfMoon") \
      ) \
     ) \
     .addChild(Transform() \
      .setRotation([1,0,0,3.14]) \
      .setTranslation([-1,0,0]) \
      .addChild(Inline() \
       .setUrl(["CircleFish.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/CircleFish.x3d","CircleFish.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/CircleFish.wrl"]) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([-2,0,0]) \
      .addChild(Inline() \
       .setUrl(["Garibaldi.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/Garibaldi.x3d","Garibaldi.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/Garibaldi.wrl"]) \
      ) \
     ) \
     .addChild(Transform() \
      .setRotation([1,0,0,3.14]) \
      .setTranslation([0,1,0]) \
      .addChild(Inline() \
       .setUrl(["HalfMoonGroup.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/HalfMoonGroup.x3d","HalfMoonGroup.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/HalfMoonGroup.wrl"]) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,-1,0]) \
      .addChild(Inline() \
       .setUrl(["KelpBass.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpBass.x3d","KelpBass.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpBass.wrl"]) \
      ) \
     ) \
     .addChild(Transform() \
      .setTranslation([0,0,1]) \
      .addChild(Inline() \
       .setUrl(["KelpSurfPerch.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpSurfPerch.x3d","KelpSurfPerch.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpSurfPerch.wrl"]) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/KelpForestExhibit//FishModelComparison_RoundTrip.x3d")
