from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("FishPrototype.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("This is a reusable prototype of a generic fish, which can be configured upon instancing to create customized fish.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Circular fish behavior is embedded in prototype, instead the circular path needs to be used in external files or possibly parameterized.") \
     .setName("warning") \
    ) \
    .addMeta(meta() \
     .setContent("Ildeniz Duman") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("Scott Tufts") \
     .setName("translator") \
    ) \
    .addMeta(meta() \
     .setContent("1 June 1998") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("9 December 2001") \
     .setName("translated") \
    ) \
    .addMeta(meta() \
     .setContent("4 May 2004") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/FishPrototype.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(ProtoDeclare() \
     .setName("Fish") \
     .setProtoInterface(ProtoInterface() \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinTextureUrl") \
       .setType("MFString") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("fishScale") \
       .setType("SFVec3f") \
       .setValue("1 1 1") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("fishColor") \
       .setType("SFColor") \
       .setValue("0.7 0.7 0.7") \
      ) \
     ) \
     .setProtoBody(ProtoBody() \
      .addChild(Transform() \
       .setDEF("FishTransform") \
       .setIS(IS() \
        .addConnect(connect() \
         .setNodeField("scale") \
         .setProtoField("fishScale") \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("Way") \
        .addChild(Transform() \
         .setTranslation([4,0,0]) \
         .addChild(Transform() \
          .setRotation([1,0,0,1.57]) \
          .addChild(Shape() \
           .setAppearance(Appearance() \
            .setMaterial(Material() \
             .setDEF("FishColor") \
             .setIS(IS() \
              .addConnect(connect() \
               .setNodeField("diffuseColor") \
               .setProtoField("fishColor") \
              ) \
             ) \
            ) \
            .setTexture(ImageTexture() \
             .setDEF("FishTexture") \
             .setIS(IS() \
              .addConnect(connect() \
               .setNodeField("url") \
               .setProtoField("skinTextureUrl") \
              ) \
             ) \
            ) \
           ) \
           .setGeometry(Extrusion(creaseAngle = 1.57, crossSection = [1.00,0.00,0.92,-0.38,0.71,-0.71,0.38,-0.92,0.00,-1.00,-0.38,-0.92,-0.71,-0.71,-0.92,-0.38,-1.00,-0.00,-0.92,0.38,-0.71,0.71,-0.38,0.92,0.00,1.00,0.38,0.92,0.71,0.71,0.92,0.38,1.00,0.00], spine = [0,3.51,0,0,3.50,0,0,2.80,0,0,2.3,0,0,1.5,0,0,0.5,0,0,0,0,0,-0.6,0]) \
            .setDEF("FishShape") \
            .setScale([0.03,0.03,0.1,0.15,0.4,0.7,0.5,0.75,0.4,0.55,0.2,0.3,0.05,0.1,0.03,0.6]) \
           ) \
          ) \
          .addChild(Shape() \
           .setAppearance(Appearance() \
            .setDEF("FinSkin") \
            .setMaterial(Material() \
             .setDiffuseColor([0.7,0.7,0.7]) \
             .setTransparency(0.3) \
            ) \
           ) \
           .setGeometry(IndexedFaceSet(coordIndex = [0,1,2,3,-1], solid = False) \
            .setCoord(Coordinate() \
             .setDEF("Pelvic") \
             .setPoint([0,2.2,0.6,0,2.2,-0.7,0,0.3,-0.3,0,0.7,0.5]) \
            ) \
           ) \
          ) \
          .addChild(Transform() \
           .setTranslation([0.3,2.8,-0.4]) \
           .addChild(Shape() \
            .setDEF("Eye") \
            .setAppearance(Appearance() \
             .setMaterial(Material() \
              .setDiffuseColor([0.5,0.5,0.5]) \
              .setShininess(1) \
              .setSpecularColor([0.3,0.3,0.3]) \
             ) \
            ) \
            .setGeometry(Sphere(radius = 0.08) \
            ) \
           ) \
          ) \
          .addChild(Transform() \
           .setTranslation([-0.3,2.8,-0.4]) \
           .addChild(Shape() \
            .setUSE("Eye") \
           ) \
          ) \
          .addChild(Transform() \
           .setScale([2.6,1,0.7]) \
           .setTranslation([0,3.44,-0.1]) \
           .addChild(Shape() \
            .setUSE("Eye") \
           ) \
          ) \
          .addChild(Transform() \
           .setDEF("LeftPectoral") \
           .setTranslation([-0.3,2.7,0.1]) \
           .addChild(Shape() \
            .setAppearance(Appearance() \
             .setUSE("FinSkin") \
            ) \
            .setGeometry(IndexedFaceSet(coordIndex = [0,1,2,-1], solid = False) \
             .setCoord(Coordinate() \
              .setPoint([0,0,0,-0.5,-0.2,0.1,-0.25,0.2,0.25]) \
             ) \
            ) \
           ) \
          ) \
          .addChild(Transform() \
           .setDEF("RightPectoral") \
           .setTranslation([0.3,2.7,0.1]) \
           .addChild(Shape() \
            .setAppearance(Appearance() \
             .setUSE("FinSkin") \
            ) \
            .setGeometry(IndexedFaceSet(coordIndex = [0,1,2,-1], solid = False) \
             .setCoord(Coordinate() \
              .setPoint([0,0,0,0.5,-0.2,0.1,0.25,0.2,0.25]) \
             ) \
            ) \
           ) \
          ) \
         ) \
        ) \
       ) \
       .addChild(Group() \
        .setDEF("AnimationGroup") \
        .addChild(TimeSensor() \
         .setDEF("RouteTImer") \
         .setCycleInterval(50) \
         .setLoop(True) \
        ) \
        .addChild(TimeSensor() \
         .setDEF("Timer") \
         .setCycleInterval(1.5) \
         .setLoop(True) \
        ) \
        .addChild(CoordinateInterpolator() \
         .setDEF("Waggler") \
         .setKey([0.0,0.5,1.0]) \
         .setKeyValue([0,3.55,0,0,3.50,0,0,2.80,0,0,2.3,0,-0.05,1.5,0,0.1,0.5,0,0.2,0,0,0.3,-0.6,0,0,3.55,0,0,3.50,0,0,2.80,0,0,2.3,0,0.05,1.5,0,-0.1,0.5,0,-0.2,0,0,-0.3,-0.6,0,0,3.55,0,0,3.50,0,0,2.80,0,0,2.3,0,-0.05,1.5,0,0.1,0.5,0,0.2,0,0,0.3,-0.6,0]) \
        ) \
        .addChild(ROUTE() \
         .setFromField("fraction_changed") \
         .setFromNode("Timer") \
         .setToField("set_fraction") \
         .setToNode("Waggler") \
        ) \
        .addChild(ROUTE() \
         .setFromField("value_changed") \
         .setFromNode("Waggler") \
         .setToField("set_spine") \
         .setToNode("FishShape") \
        ) \
        .addChild(CoordinateInterpolator() \
         .setDEF("Points") \
         .setKey([0.0,0.5,1.0]) \
         .setKeyValue([0,2.2,0.6,0,2.2,-0.7,0.2,0.3,-0.3,0.2,0.7,0.5,0,2.2,0.6,0,2.2,-0.7,-0.2,0.3,-0.3,-0.2,0.7,0.5,0,2.2,0.6,0,2.2,-0.7,0.2,0.3,-0.3,0.2,0.7,0.5]) \
        ) \
        .addChild(ROUTE() \
         .setFromField("fraction_changed") \
         .setFromNode("Timer") \
         .setToField("set_fraction") \
         .setToNode("Points") \
        ) \
        .addChild(ROUTE() \
         .setFromField("value_changed") \
         .setFromNode("Points") \
         .setToField("set_point") \
         .setToNode("Pelvic") \
        ) \
        .addChild(OrientationInterpolator() \
         .setDEF("LeftPectoralRotation") \
         .setKey([0,0.3,0.7,1]) \
         .setKeyValue([0,1,0,0.523,0,1,0,0,0,1,0,0,0,1,0,0.523]) \
        ) \
        .addChild(ROUTE() \
         .setFromField("fraction_changed") \
         .setFromNode("Timer") \
         .setToField("set_fraction") \
         .setToNode("LeftPectoralRotation") \
        ) \
        .addChild(ROUTE() \
         .setFromField("value_changed") \
         .setFromNode("LeftPectoralRotation") \
         .setToField("set_rotation") \
         .setToNode("LeftPectoral") \
        ) \
        .addChild(OrientationInterpolator() \
         .setDEF("RightPectoralRotation") \
         .setKey([0,0.3,0.7,1]) \
         .setKeyValue([0,1,0,-0.523,0,1,0,0,0,1,0,0,0,1,0,-0.523]) \
        ) \
        .addChild(ROUTE() \
         .setFromField("fraction_changed") \
         .setFromNode("Timer") \
         .setToField("set_fraction") \
         .setToNode("RightPectoralRotation") \
        ) \
        .addChild(ROUTE() \
         .setFromField("value_changed") \
         .setFromNode("RightPectoralRotation") \
         .setToField("set_rotation") \
         .setToNode("RightPectoral") \
        ) \
        .addChild(OrientationInterpolator() \
         .setDEF("Turn") \
         .setKey([0,0.25,0.5,0.75,1]) \
         .setKeyValue([0,1,0,0,0,1,0,-1.57,0,1,0,-3.14,0,1,0,-4.71,0,1,0,0]) \
        ) \
        .addChild(ROUTE() \
         .setFromField("fraction_changed") \
         .setFromNode("RouteTImer") \
         .setToField("set_fraction") \
         .setToNode("Turn") \
        ) \
        .addChild(ROUTE() \
         .setFromField("value_changed") \
         .setFromNode("Turn") \
         .setToField("set_rotation") \
         .setToNode("Way") \
        ) \
       ) \
      ) \
     ) \
    ) \
# ==================== 
    .addChild(ProtoInstance() \
     .setName("Fish") \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/KelpForestExhibit//FishPrototype_RoundTrip.x3d")
