from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("KelpPrototype.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Creates Kelp Prototype - this file uses Bulb and is used by KelpExamplesNoBase.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Joseph Cannon, Dan DeVos") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("18 March 1999") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("5 October 2015") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://faculty.nps.edu/brutzman/kelp") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("KelpForestDesignPaperWeb3dSymposiumFebruary2002.pdf") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpForestDesignPaperWeb3dSymposiumFebruary2002.pdf") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/Teaching3d-KelpForestCaseStudy.pdf") \
     .setName("reference") \
    ) \
    .addMeta(meta() \
     .setContent("All content has permissions for free use. Please provide credit to the Naval Postgraduate School (NPS) Modeling Virtual Environments and Simulation (MOVES) Institute.") \
     .setName("accessRights") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpPrototype.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("Vrml97ToX3dNist, http://ovrt.nist.gov/v2_x3d.html") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(ProtoDeclare() \
     .setAppinfo("Kelp strands and bulbs with no base") \
     .setName("Kelp") \
     .setProtoInterface(ProtoInterface() \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("frontBladeSize") \
       .setType("SFVec3f") \
       .setValue("0.7 0.7 0.7") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("frontSideBladeHeight") \
       .setType("SFVec3f") \
       .setValue("0 4 0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("rightBladeSize") \
       .setType("SFVec3f") \
       .setValue("0.7 0.7 0.7") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("rightSideBladeHeight") \
       .setType("SFVec3f") \
       .setValue("0 12 0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("rearBladeSize") \
       .setType("SFVec3f") \
       .setValue("0.4 0.4 0.4") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("rearSideBladeHeight") \
       .setType("SFVec3f") \
       .setValue("0 20 0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("leftBladeSize") \
       .setType("SFVec3f") \
       .setValue("0.4 0.4 0.4") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("leftSideBladeHeight") \
       .setType("SFVec3f") \
       .setValue("0 24 0") \
      ) \
     ) \
     .setProtoBody(ProtoBody() \
      .addChild(Group() \
       .addChild(Transform() \
        .setDEF("stipe") \
        .setCenter([0,-16,0]) \
        .setTranslation([0,14,0]) \
        .addChild(Shape() \
         .setDEF("stemShape") \
         .setAppearance(Appearance() \
          .setDEF("kelpColor") \
          .setMaterial(Material() \
           .setDiffuseColor([0.882,0.757,0.184]) \
          ) \
         ) \
         .setGeometry(Cylinder(bottom = False, height = 28.0, radius = 0.2) \
          .setTop(False) \
         ) \
        ) \
        .addChild(Transform() \
         .setDEF("horizontalStipe") \
         .setCenter([0,16,0]) \
         .setRotation([0,0,1,1.5707]) \
         .setScale([0.5,0.3,0.5]) \
         .setTranslation([1.3,0,0]) \
         .addChild(Transform() \
          .addChild(Shape() \
           .setUSE("stemShape") \
          ) \
         ) \
         .addChild(Transform() \
          .setDEF("blade_X1") \
          .setRotation([0,1,0,1.0]) \
          .setTranslation([0,12,0]) \
          .addChild(Transform() \
           .setDEF("bladeRotateZ") \
           .setRotation([0,0,1,-1.2]) \
           .addChild(Transform() \
            .setDEF("BLADE") \
            .setCenter([-0.5,0,0]) \
            .setTranslation([1,0,0]) \
            .addChild(Inline() \
             .setDEF("bulb") \
             .setUrl(["KelpBulb.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpBulb.x3d","KelpBulb.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpBulb.wrl"]) \
            ) \
           ) \
          ) \
         ) \
         .addChild(Transform() \
          .setDEF("blade_X2") \
          .setRotation([0,1,0,-1.0]) \
          .addChild(Transform() \
           .setUSE("bladeRotateZ") \
          ) \
         ) \
         .addChild(Transform() \
          .setDEF("blade_X3") \
          .setRotation([0,1,0,4.342]) \
          .setTranslation([0,-12,0]) \
          .addChild(Transform() \
           .setUSE("bladeRotateZ") \
          ) \
         ) \
        ) \
        .addChild(Transform() \
         .setTranslation([0,14,0]) \
         .addChild(Shape() \
          .setAppearance(Appearance() \
           .setUSE("kelpColor") \
          ) \
          .setGeometry(Extrusion(creaseAngle = 1.57, crossSection = [0.2,0,0.184,-0.076,0.142,-0.142,0.076,-0.184,0,-0.2,-0.076,-0.184,-0.142,-0.142,-0.184,-0.076,-0.2,-0,-0.184,0.076,-0.142,0.142,-0.076,0.184,0,0.2,0.076,0.184,0.142,0.142,0.184,0.076,0.2,0], spine = [0,0,0,0.15,0.77,0,0.59,1.41,0,1.23,1.85,0,2,2,0]) \
           .setScale([1,1,0.8,0.8,0.7,0.7,0.6,0.6,0.5,0.5]) \
          ) \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("blade_Y1") \
        .setRotation([0,0,1,1.2]) \
        .setIS(IS() \
         .addConnect(connect() \
          .setNodeField("scale") \
          .setProtoField("frontBladeSize") \
         ) \
         .addConnect(connect() \
          .setNodeField("translation") \
          .setProtoField("frontSideBladeHeight") \
         ) \
        ) \
        .addChild(Transform() \
         .setUSE("BLADE") \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("blade_Y2") \
        .setRotation([0,1,0,4.2]) \
        .setIS(IS() \
         .addConnect(connect() \
          .setNodeField("scale") \
          .setProtoField("rightBladeSize") \
         ) \
         .addConnect(connect() \
          .setNodeField("translation") \
          .setProtoField("rightSideBladeHeight") \
         ) \
        ) \
        .addChild(Transform() \
         .setDEF("bladeToTheSide") \
         .setRotation([1,0,0,3.142]) \
         .addChild(Transform() \
          .setRotation([0,0,1,-1.2]) \
          .addChild(Transform() \
           .setDEF("rotateBlade90") \
           .setCenter([-0.5,0,0]) \
           .setRotation([1,0,0,1.5707]) \
           .setTranslation([1,0,0]) \
           .addChild(Inline() \
            .setUSE("bulb") \
           ) \
          ) \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("blade_Y3") \
        .setRotation([0,1,0,3.2]) \
        .setIS(IS() \
         .addConnect(connect() \
          .setNodeField("scale") \
          .setProtoField("rearBladeSize") \
         ) \
         .addConnect(connect() \
          .setNodeField("translation") \
          .setProtoField("rearSideBladeHeight") \
         ) \
        ) \
        .addChild(Transform() \
         .setDEF("Blade-Z") \
         .setRotation([1,0,0,3.142]) \
         .addChild(Transform() \
          .setRotation([0,0,1,-1.2]) \
          .addChild(Transform() \
           .setUSE("BLADE") \
          ) \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setDEF("blade_Y4") \
        .setRotation([0,1,0,1.2]) \
        .setIS(IS() \
         .addConnect(connect() \
          .setNodeField("scale") \
          .setProtoField("leftBladeSize") \
         ) \
         .addConnect(connect() \
          .setNodeField("translation") \
          .setProtoField("leftSideBladeHeight") \
         ) \
        ) \
        .addChild(Transform() \
         .setUSE("bladeToTheSide") \
        ) \
       ) \
       .addChild(TimeSensor() \
        .setDEF("Clock") \
        .setCycleInterval(5.5) \
        .setLoop(True) \
       ) \
       .addChild(OrientationInterpolator() \
        .setDEF("horizontalStipeMover") \
        .setKey([0,0.25,0.5,0.75,1.0]) \
        .setKeyValue([0,0,1,1.471,0,0,1,1.571,0,0,1,1.671,0,0,1,1.571,0,0,1,1.471]) \
       ) \
      ) \
      .addChild(ROUTE() \
       .setFromField("fraction_changed") \
       .setFromNode("Clock") \
       .setToField("set_fraction") \
       .setToNode("horizontalStipeMover") \
      ) \
      .addChild(ROUTE() \
       .setFromField("value_changed") \
       .setFromNode("horizontalStipeMover") \
       .setToField("set_rotation") \
       .setToNode("horizontalStipe") \
      ) \
     ) \
    ) \
# Example use of this prototype is in KelpNoBase.x3d, .wrl 
    .addChild(Viewpoint() \
     .setDescription("click message to view example") \
     .setPosition([0,0,8]) \
    ) \
# Redirection text in case a user examines this PROTO file via a 3D browser: 
    .addChild(Anchor() \
     .setDEF("TouchTextForExample") \
     .setDescription("KelpNoBase") \
     .setParameter(["target=_blank"]) \
     .setUrl(["KelpExamplesNoBase.x3d","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpExamplesNoBase.x3d","KelpExamplesNoBase.wrl","http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/KelpExamplesNoBase.wrl"]) \
     .addChild(Shape() \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
        .setDiffuseColor([0,1,1]) \
        .setEmissiveColor([0,1,1]) \
       ) \
      ) \
      .setGeometry(Text() \
       .setString(["KelpPrototype","is a Prototype declaration file.","","To see an example using 3 instances of","this new node, click this text and view","KelpNoBase scene"]) \
       .setFontStyle(FontStyle(justify = ["MIDDLE","MIDDLE"], size = 0.5) \
       ) \
      ) \
     ) \
# Selectable Text design pattern has transparent Box and TouchSensor description as a tooltip 
     .addChild(Shape() \
      .setGeometry(Box(size = [8,3,.001]) \
      ) \
      .setAppearance(Appearance() \
       .setMaterial(Material() \
        .setTransparency(1) \
       ) \
      ) \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/KelpForestExhibit//KelpPrototype_RoundTrip.x3d")
