from X3Dautoclass import *
X3D0 = X3D() \
   .setProfile("Immersive") \
   .setVersion("3.3") \
   .setHead(head() \
    .addMeta(meta() \
     .setContent("SeaStarPrototype.x3d") \
     .setName("title") \
    ) \
    .addMeta(meta() \
     .setContent("Prototype of a simple SeaStar. Zoom in to inspect.") \
     .setName("description") \
    ) \
    .addMeta(meta() \
     .setContent("Karl Tenney") \
     .setName("creator") \
    ) \
    .addMeta(meta() \
     .setContent("Scott Tufts") \
     .setName("translator") \
    ) \
    .addMeta(meta() \
     .setContent("17 December 2001") \
     .setName("created") \
    ) \
    .addMeta(meta() \
     .setContent("13 December 2001") \
     .setName("translated") \
    ) \
    .addMeta(meta() \
     .setContent("10 January 2014") \
     .setName("modified") \
    ) \
    .addMeta(meta() \
     .setContent("http://X3dGraphics.com/examples/X3dForWebAuthors/KelpForestExhibit/SeaStarPrototype.x3d") \
     .setName("identifier") \
    ) \
    .addMeta(meta() \
     .setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit") \
     .setName("generator") \
    ) \
    .addMeta(meta() \
     .setContent("../license.html") \
     .setName("license") \
    ) \
   ) \
   .setScene(Scene() \
    .addChild(ProtoDeclare() \
     .setName("SeaStar") \
     .setProtoInterface(ProtoInterface() \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinDiffuseColor") \
       .setType("SFColor") \
       .setValue("0.8 0.8 0.8") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinSpecularColor") \
       .setType("SFColor") \
       .setValue("0 0 0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinEmissiveColor") \
       .setType("SFColor") \
       .setValue("0 0 0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinShininess") \
       .setType("SFFloat") \
       .setValue("0.2") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinTransparency") \
       .setType("SFFloat") \
       .setValue("0") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("skinTextureUrl") \
       .setType("MFString") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("translation") \
       .setType("SFVec3f") \
       .setValue("0.00319815 0.00994461 0.0067411") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("rotation") \
       .setType("SFRotation") \
       .setValue("-0.32376 -0.32376 0.889021 1.68816") \
      ) \
      .addField(field() \
       .setAccessType("inputOutput") \
       .setName("scale") \
       .setType("SFVec3f") \
       .setValue("0.659575 0.659575 0.659575") \
      ) \
     ) \
     .setProtoBody(ProtoBody() \
      .addChild(Transform() \
       .setDEF("SeaStarLocation") \
       .setIS(IS() \
        .addConnect(connect() \
         .setNodeField("translation") \
         .setProtoField("translation") \
        ) \
        .addConnect(connect() \
         .setNodeField("rotation") \
         .setProtoField("rotation") \
        ) \
        .addConnect(connect() \
         .setNodeField("scale") \
         .setProtoField("scale") \
        ) \
       ) \
       .addChild(Transform() \
        .setRotation([1.14191e-007,-1,-5.32201e-006,0.814114]) \
        .setScale([0.0276058,0.0102856,0.0774523]) \
        .setTranslation([-0.0454274,0.0102855,0.0416858]) \
        .addChild(Shape() \
         .setDEF("SeaStarLeg") \
         .setAppearance(Appearance() \
          .setMaterial(Material() \
           .setDEF("skinColor") \
           .setIS(IS() \
            .addConnect(connect() \
             .setNodeField("diffuseColor") \
             .setProtoField("skinDiffuseColor") \
            ) \
            .addConnect(connect() \
             .setNodeField("specularColor") \
             .setProtoField("skinSpecularColor") \
            ) \
            .addConnect(connect() \
             .setNodeField("emissiveColor") \
             .setProtoField("skinEmissiveColor") \
            ) \
            .addConnect(connect() \
             .setNodeField("shininess") \
             .setProtoField("skinShininess") \
            ) \
            .addConnect(connect() \
             .setNodeField("transparency") \
             .setProtoField("skinTransparency") \
            ) \
           ) \
          ) \
          .setTexture(ImageTexture() \
           .setDEF("skinTexture") \
           .setIS(IS() \
            .addConnect(connect() \
             .setNodeField("url") \
             .setProtoField("skinTextureUrl") \
            ) \
           ) \
          ) \
         ) \
         .setGeometry(Sphere() \
         ) \
        ) \
       ) \
       .addChild(Transform() \
        .setRotation([1.6646e-007,1,6.79179e-007,0.915243]) \
        .setScale([0.0276058,0.0102856,0.118301]) \
        .setTranslation([-0.0731081,0.0102856,-0.047631]) \
        .addChild(Shape() \
         .setUSE("SeaStarLeg") \
        ) \
       ) \
       .addChild(Transform() \
        .setScale([0.0276058,0.0102856,0.118301]) \
        .setTranslation([-1.21519e-009,0.0102856,-0.086997]) \
        .addChild(Shape() \
         .setUSE("SeaStarLeg") \
        ) \
       ) \
       .addChild(Transform() \
        .setRotation([7.02699e-008,1,-9.67549e-009,4.71239]) \
        .setScale([0.0276058,0.0102856,0.118301]) \
        .setTranslation([0.0943676,0.0102856,-9.2235e-010]) \
        .addChild(Shape() \
         .setUSE("SeaStarLeg") \
        ) \
       ) \
       .addChild(Transform() \
        .setRotation([-2.28035e-007,1,-1.9708e-007,0.399743]) \
        .setScale([0.0276058,0.0102856,0.118301]) \
        .setTranslation([0.0273156,0.0102856,0.0869062]) \
        .addChild(Shape() \
         .setUSE("SeaStarLeg") \
        ) \
       ) \
       .addChild(Transform() \
        .setRotation([1.74007e-006,-1,-1.7261e-007,0.240595]) \
        .setScale([0.0564878,0.00994367,0.0245735]) \
        .setTranslation([-0.12392,0.00994368,0.0707975]) \
        .addChild(Shape() \
         .setUSE("SeaStarLeg") \
        ) \
       ) \
      ) \
     ) \
    ) \
# ==================== 
    .addChild(ProtoInstance() \
     .setName("SeaStar") \
     .addFieldValue(fieldValue() \
      .setName("rotation") \
      .setValue("0 1 0 0") \
     ) \
    ) \
   ) \

X3D0.toFileX3D("/x3d-code/www.web3d.org/x3d/content/examples/X3dForWebAuthors/KelpForestExhibit//SeaStarPrototype_RoundTrip.x3d")
